### ISSUE TITLE
Only does the first 100 Contacts

### ISSUE THREAD

**Issue by philhop1** [msp4msps/Syncro-Documentation#1]
Hi I just wanted to address this , awsome script however it only returns 100 contacts.

Sorry I posted this to your youtube channel aswell. 

The code is wrong. Syncro returns 100 customer per page. The number of pages is returned in the first call, you then have to step through the pages.

So you need code in there that would look something like
$Syncro = Invoke-RestMethod -Uri "$apiUri/customers" -Method Get -Header @{ "Authorization" = $SyncroAPIKey } -ContentType "application/json"
$SyncroCustomerList = $Syncro.customers
if ($Syncro.meta.total_pages -gt 1) {
for($i=2; $i -le $Syncro.meta.total_pages; $i++){
$SyncroCustomerList += (Invoke-RestMethod -Method Get -Uri "$apiUri/customers?page=$i" -Header @{ "Authorization" = $SyncroAPIKey } -ContentType "application/json").customers
}
}
With that info you probably can fix the issue, however it looks like the author is pretty active in this repo, you should open an issue explaining the problem your having and suggesting the fix it you understand it well enough to explain it. (For all the functionality this guy wrote into his script I'm sure he can figure out a good way to fix the issue himself if he is made aware of the issue).

**Comment by msp4msps** [comment]
Updated script to handle any company or contact size
